"""initial model

Revision ID: 1f5244c893ac
Revises: 1b63c02f7381
Create Date: 2024-01-16 12:16:18.475836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5244c893ac'
down_revision = '1b63c02f7381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_missions_scientist_id_scientists', 'missions', type_='foreignkey')
    op.drop_constraint('fk_missions_planet_id_planets', 'missions', type_='foreignkey')
    op.drop_column('missions', 'scientist_id')
    op.drop_column('missions', 'planet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('planet_id', sa.INTEGER(), nullable=True))
    op.add_column('missions', sa.Column('scientist_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('fk_missions_planet_id_planets', 'missions', 'planets', ['planet_id'], ['id'])
    op.create_foreign_key('fk_missions_scientist_id_scientists', 'missions', 'scientists', ['scientist_id'], ['id'])
    # ### end Alembic commands ###
